Update MathComponent.cpp
Crew-M2D/intersection-of-2-triangles pull request #8
Opened 2023-04-27 22:09 UTC by 2Ez4Joker

MathComponent changes.

2023-04-28 09:29 UTC, kamawwanai requested changes
Поправь, пожалуйста, в соответствие с комментариями

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +double cross_product(Point2f a, Point2f b, Point2f c) {
Переменные не говорящие не понятно, что такое a,b,c

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	double ax = b.x - a.x;
код стайл ax - плохо, a_x - хорошо

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	for (int i = 0;i < 2;++i)
отсутствует форматирование кода во всей этой функции, тяжело в целом смотреть код

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	double cp1 = cross_product(a, b, p);
опять же название переменных (расшифровку cp лучше не искать в интернете)

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
>      (void)triangle_1;
вот эту строчку надо убрать, она ничего не делает

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
>      (void)triangle_2;
и эту

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	max_y = max(max_y, abs(triangle_2[2].y));
Во-первых, не подключено пространство имен std, и не нужно его подключать, поэтому пиши `std::max` и `std::abs`
Во-вторых, для функции `std::max()` необходимо `#include <algorithm>`
В `std::max()` можно передавать initializer_list и не писать так много повторяющихся точек, например,
`std::max({1.F,2.F,3.F})`

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	float kaef = 400/max(max_y, max_x);
название переменных, транслит лучше вообще не использовать.
коэффициент можно перевести как coefficient или ratio.

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
>      (void)triangle_1;
как и в прошлой функции, эту строчку необходимо убрать, она ничего не делает

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
>      (void)triangle_2;
эту тоже

2023-04-28 09:29 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +				}
Во-первых, можно использовать else if, ведь если indicator стал false на условиях до, то остальные проверки не нужны.
Во-вторых, std::max() и std::min(), подробное объяснение написала в одном из комментариев ниже.

2023-04-28 13:17 UTC, 2Ez4Joker reviewed
Незаметил что только первую переменную исправил. Поправил.

2023-04-28 14:08 UTC, kamawwanai requested changes
В целом, хорошо исправил, вот еще немного и будет идеально.

2023-04-28 14:08 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	for (int i = 0;i < 2;++i)
код до сих пор не отформатирован, в vscode для этого нажми сочетание клавиш shift+alt+F

2023-04-28 14:08 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +			if ((first_point_x_1 - second_point_x_1) * (first_point_y_2 - second_point_y_2) - (first_point_y_1 - second_point_y_2) * (first_point_x_2 - second_point_x_2) != 0)
также разбей условия на функции с говорящими названиями.
Приятнее читать if (is_on_one_line(point1, point2)) или наподобие. Зависит от того, что твоя функция делает

2023-04-28 14:08 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	for (int i = 0;i < 2;++i)
не забудь поставить для этого расширение clangd и отключить все расширение для C++ от microsoft. Они конфликтуют.

2023-04-28 14:08 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +			if ((first_point_x_1 - second_point_x_1) * (first_point_y_2 - second_point_y_2) - (first_point_y_1 - second_point_y_2) * (first_point_x_2 - second_point_x_2) != 0)
это касается и последующих условий

2023-04-28 14:08 UTC, kamawwanai commented on src/Math/MathComponent.cpp
> +	std::vector<Point2f> Intersection_points;
для этого используется Intersection, объявленный в <Common.hpp>

2023-05-01 17:30 UTC, 2Ez4Joker commented
Поправлено.

2023-05-01 19:01 UTC, kamawwanai approved these changes
Молодец, спасибо!
![45498d0c94602e5474f70105b670c310.jpg](https://user-images.githubusercontent.com/87859313/235511819-94dcffe2-fefb-4be6-bdfb-f2f473dcfa44.jpg)

2023-05-04 12:15 UTC, 2Ez4Joker commented
Была опечатка в переменной. + Попросили сортировку точек сделать

2023-05-06 16:18 UTC, merged